sudo: required

services:
  - docker

language: ruby

rvm:
  - 2.2.1

before_install:
  - script/setup

script:
  - docker-compose up -d web
  - [ $(curl -sL -w "%{http_code}" http://localhost:3000/ -o /dev/null) -eq 200 ] || exit 1
