version: '2'

services:
  app:
    build: .
    container_name: columbusrb.com-app
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    links:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres/crb_development?pool=5

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
